"""Structural contracts for the five independent task execution extensions."""

from collections.abc import Mapping
from typing import Any, Protocol

from loom.runtime.execution_contracts import ToolExecutionRuntime
from loom.runtime.plugin_contracts import PluginManifest


class SessionEnvironment(Protocol):
    manifest: PluginManifest

    def open(self) -> Any: ...

    def resources(self) -> tuple: ...

    def claims(self) -> tuple: ...

    def snapshot(self) -> dict: ...

    def restore(self, state: Mapping) -> None: ...

    def reconnect(self) -> bool: ...

    async def close(self) -> None: ...


class ContextManager(Protocol):
    manifest: PluginManifest

    def project(self, context: Any) -> list: ...

    def compact(self, messages: list, limit: int, *, schema_chars: int = 0) -> tuple: ...

    def ingest(self, context: Any, committed_result: Any) -> Any: ...

    def snapshot(self) -> dict: ...

    def restore(self, state: Mapping) -> None: ...


class ToolCollection(Protocol):
    manifest: PluginManifest
    entrypoints: Mapping

    def catalog(self, environment: Any = None) -> Any: ...

    def bindings(self) -> tuple: ...

    def reconcile(self, operation: Any, evidence: Any) -> dict: ...

    def snapshot(self) -> dict: ...

    def restore(self, state: Mapping) -> None: ...


class WorkflowPolicy(Protocol):
    manifest: PluginManifest

    def tool_refs(self) -> tuple: ...

    def configure_normal_tool_refs(self, refs: tuple) -> None: ...

    def visible_tool_refs(self, refs: tuple) -> tuple: ...

    def wrap_tools(self, handlers: Mapping) -> Mapping: ...

    def wrap_loop(self, definition: Any) -> Any: ...

    def project_state(self, context: Any) -> Any: ...

    def unfinished(self) -> bool: ...

    def snapshot(self) -> dict: ...

    def restore(self, state: Mapping) -> Any: ...

    def plugin_snapshot(self) -> dict: ...

    def restore_plugin(self, state: Mapping) -> None: ...


__all__ = ["ContextManager", "SessionEnvironment", "ToolCollection", "ToolExecutionRuntime", "WorkflowPolicy"]
