"""Evolution public API for Loom."""

from loom.evolution._exports import lazy_analyze_export
from loom.evolution.episodes import StepEpisode, TraceRecord, build_step_episodes, load_trace_records
from loom.evolution.mutations import (
    CompositionEdge,
    CompositionGraph,
    CompositionNode,
    ContextMutation,
    DefaultEvolutionEvaluator,
    EvolutionDecision,
    EvolutionEvaluation,
    InMemoryImplementationRegistry,
    InMemoryLoopRegistry,
    LoopMutation,
    MutationBundle,
    MutationPolicy,
    MutationTransaction,
    ScoreSummary,
    ShadowEvaluationResult,
    ShadowSummary,
    StructureMutation,
    apply_loop_mutation,
    apply_structure_mutation,
    decide_evolution,
    run_shadow_evaluation,
    validate_composition_graph,
    validate_mutation_bundle_shape,
)
from loom.evolution.proposals import EvolutionProposal, EvolutionSignal, ProposalGateConfig
from loom.evolution.scoring import LlmStepScorer, StepScore

__getattr__ = lazy_analyze_export(globals())

__all__ = [
    "AnalyzeConfig",
    "AnalyzeResult",
    "AnalyzeRunOptions",
    "CompositionEdge",
    "CompositionGraph",
    "CompositionNode",
    "ContextMutation",
    "DefaultEvolutionEvaluator",
    "EvolutionDecision",
    "EvolutionEvaluation",
    "EvolutionProposal",
    "EvolutionSignal",
    "InMemoryImplementationRegistry",
    "InMemoryLoopRegistry",
    "LlmStepScorer",
    "LoopMutation",
    "MutationBundle",
    "MutationPolicy",
    "MutationTransaction",
    "ProposalGateConfig",
    "ScoreSummary",
    "ShadowEvaluationResult",
    "ShadowSummary",
    "StepEpisode",
    "StepScore",
    "StructureMutation",
    "TraceRecord",
    "apply_loop_mutation",
    "apply_structure_mutation",
    "analyze_trace",
    "build_step_episodes",
    "decide_evolution",
    "load_trace_records",
    "main",
    "parse_args",
    "parse_run_options",
    "run_analyze_trace_with_tui",
    "run_shadow_evaluation",
    "validate_composition_graph",
    "validate_mutation_bundle_shape",
]
